DROP TABLE IF EXISTS RESPONSE_DATA;  
CREATE TABLE RESPONSE_DATA (  
id NUMBER,
req_type  VARCHAR2(200) NOT NULL,
req_param VARCHAR2(200) NOT NULL,
res_param VARCHAR2(200) ,
created_on TIMESTAMP NULL,
PRIMARY KEY (id)
);  